FROM openjdk:8

ARG HIVE_VERSION
ENV HIVE_VERSION=${HIVE_VERSION:-3.1.2}

ENV HIVE_HOME /opt/hive
ENV PATH $HIVE_HOME/bin:$PATH
ENV HADOOP_HOME /opt/hadoop
ENV PATH $HADOOP_HOME/bin:$PATH
ENV HADOOP_PREFIX=$HADOOP_HOME
ENV HADOOP_CONF_DIR=/etc/hadoop
# ENV USER=root
# ENV MULTIHOMED_NETWORK=1


WORKDIR /opt

# install hadoop
COPY hadoop-$HIVE_VERSION.tar.gz /opt/
RUN tar -zxvf /opt/hadoop-$HIVE_VERSION.tar.gz
RUN ln -s /opt/hadoop-$HIVE_VERSION $HADOOP_HOME
RUN ln -s /opt/hadoop-$HIVE_VERSION/etc/hadoop /etc/hadoop

# install hive
COPY apache-hive-$HIVE_VERSION-bin.tar.gz /opt/
RUN tar -zxvf /opt/apache-hive-$HIVE_VERSION-bin.tar.gz
RUN ln -s /opt/apache-hive-$HIVE_VERSION-bin $HIVE_HOME
COPY hive-exec-3.1.2-ignoreAlterTableSerdeError.jar /opt/hive/lib/

RUN apt-get update && apt-get install -y --force-yes wget procps netcat net-tools

#Custom configuration goes here
ADD conf/hive-site.xml $HIVE_HOME/conf
ADD conf/beeline-log4j2.properties $HIVE_HOME/conf
ADD conf/hive-env.sh $HIVE_HOME/conf
ADD conf/hive-exec-log4j2.properties $HIVE_HOME/conf
ADD conf/hive-log4j2.properties $HIVE_HOME/conf
ADD conf/ivysettings.xml $HIVE_HOME/conf
ADD conf/llap-daemon-log4j2.properties $HIVE_HOME/conf

COPY startup-hiveserver2.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/startup-hiveserver2.sh

COPY entrypoint-hiveserver2.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

EXPOSE 10000
EXPOSE 10002

ENTRYPOINT ["entrypoint.sh"]
CMD startup-hiveserver2.sh
